# Generated by Django 3.0.7 on 2021-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16, verbose_name='분류')),
                ('content', models.CharField(max_length=64, verbose_name='내용')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='수정일자')),
            ],
        ),
    ]
