# Generated by Django 3.0.7 on 2021-11-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='register_dttm',
            field=models.DateField(auto_now_add=True, verbose_name='수정일자'),
        ),
    ]
