# Generated by Django 3.0.7 on 2021-11-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211103_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='title',
        ),
    ]
