# Generated by Django 3.0.7 on 2021-12-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211214_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_summary',
            field=models.TextField(null=True, verbose_name='요약'),
        ),
    ]
